# images can be found in https://github.com/walkxcode/dashboard-icons

- Group hypervisor:
  - proxmox:
    icon: proxmox.png 
    href: https://192.168.0.200:8006
    description: proxmox VE main

- Group websites:
  - NPM:
  #  icon: npm

  - AquaWebDashboard:
  # icon: 
    href: https://AquaWebDashboard/cozmicxzelectronics.uk
    description: shows data on fishtank
- Group Games:
  - minecraft server 1:
  #  icon: 
    description: minecraft server 1 (friend server)

- Group Networking:
